# Generated by Django 2.0 on 2018-07-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20180704_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
