# Generated by Django 2.0.4 on 2018-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('phn_numb', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(default='pass', max_length=100)),
            ],
        ),
    ]
