# Generated by Django 2.0.4 on 2018-05-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pass', max_length=100),
        ),
    ]
